name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
          run_install: true

      - name: Build Extension
        run: pnpm build

      - name: Make Zip
        run: pnpm zip

      - name: Publish Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "extension.zip"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
